# Test confirmation endpoint
$baseUrl = "http://localhost:5185"

# Test with a sample token (this would normally be generated by the system)
# For testing, let's create a simple test token
$testToken = "test-token-123"

Write-Host "Testing confirmation endpoint..."
Write-Host "URL: $baseUrl/confirm?t=$testToken"

try {
    $response = Invoke-WebRequest -Uri "$baseUrl/confirm?t=$testToken" -Method GET
    Write-Host "Status: $($response.StatusCode)"
    Write-Host "Content: $($response.Content)"
} catch {
    Write-Host "Error: $($_.Exception.Message)"
    Write-Host "Response: $($_.Exception.Response)"
}
