// <auto-generated />
using System;
using AlertSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlertSystem.DataLayer.DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251026192758_AddAlertSystemSchemaToHotelDB")]
    partial class AddAlertSystemSchemaToHotelDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlertSystem.Entities.Entities.AlertProcessingQueue", b =>
                {
                    b.Property<int>("QueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QueueId"));

                    b.Property<int>("AlertRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("QueueId");

                    b.HasIndex("AlertRecordId");

                    b.HasIndex("Priority", "QueuedAt");

                    b.ToTable("AlertProcessingQueue", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.AlertType", b =>
                {
                    b.Property<int>("AlertTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertTypeId"));

                    b.Property<string>("AlertTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AlertType");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAcknowledgment")
                        .HasColumnType("bit");

                    b.HasKey("AlertTypeId");

                    b.ToTable("AlertType", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.Alerte", b =>
                {
                    b.Property<int>("AlertRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertRecordId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertRecordId"));

                    b.Property<Guid>("AlertGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreationAlerte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionAlerte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinataireDesktop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinataireEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinatairePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DestinataireUserId")
                        .HasColumnType("int");

                    b.Property<int>("EtatAlerteId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<int>("PlateformeEnvoieId")
                        .HasColumnType("int");

                    b.Property<int?>("PlateformeEnvoiePlateformeId")
                        .HasColumnType("int");

                    b.Property<bool>("ProcessedByWorker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RappelSuivant")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatutId")
                        .HasColumnType("int");

                    b.Property<string>("TitreAlerte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlertRecordId");

                    b.HasIndex("AlertGroupId");

                    b.HasIndex("AlertTypeId");

                    b.HasIndex("DestinataireUserId");

                    b.HasIndex("EtatAlerteId");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("PlateformeEnvoieId");

                    b.HasIndex("PlateformeEnvoiePlateformeId");

                    b.HasIndex("StatutId", "ProcessedByWorker", "DateCreationAlerte");

                    b.ToTable("Alerte", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.ApiClient", b =>
                {
                    b.Property<int>("ApiClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiClientId"));

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RateLimitPerMinute")
                        .HasColumnType("int");

                    b.HasKey("ApiClientId");

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.DefUtilisateur", b =>
                {
                    b.Property<int>("util_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("util_id"));

                    b.Property<bool>("util_actif")
                        .HasColumnType("bit")
                        .HasColumnName("util_actif");

                    b.Property<string>("util_email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("util_email");

                    b.Property<string>("util_nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("util_nom");

                    b.Property<string>("util_telephone_portable")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("util_telephone_portable");

                    b.HasKey("util_id");

                    b.ToTable("def_utilisateur", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.Etat", b =>
                {
                    b.Property<int>("EtatAlerteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EtatAlerteId"));

                    b.Property<string>("EtatAlerteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EtatAlerte");

                    b.HasKey("EtatAlerteId");

                    b.ToTable("Etat", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.PlateformeEnvoie", b =>
                {
                    b.Property<int>("PlateformeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlateformeId"));

                    b.Property<string>("Plateforme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PlateformeId");

                    b.ToTable("PlateformeEnvoie", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.RappelSuivant", b =>
                {
                    b.Property<int>("RappelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RappelId"));

                    b.Property<int>("AlertRecordId")
                        .HasColumnType("int");

                    b.Property<int>("AlerteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRappel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DetailsErreur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatutRappel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tentative")
                        .HasColumnType("int");

                    b.HasKey("RappelId");

                    b.HasIndex("AlerteId");

                    b.ToTable("RappelSuivant", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.Statut", b =>
                {
                    b.Property<int>("StatutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatutId"));

                    b.Property<string>("StatutName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Statut");

                    b.HasKey("StatutId");

                    b.ToTable("Statut", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.WebPushSubscription", b =>
                {
                    b.Property<int>("WebPushSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WebPushSubscriptionId"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WebPushSubscriptionId");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("WebPushSubscriptions", (string)null);
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.Alerte", b =>
                {
                    b.HasOne("AlertSystem.Entities.Entities.AlertType", "AlertType")
                        .WithMany()
                        .HasForeignKey("AlertTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AlertSystem.Entities.Entities.DefUtilisateur", "DestinataireUser")
                        .WithMany()
                        .HasForeignKey("DestinataireUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlertSystem.Entities.Entities.Etat", "Etat")
                        .WithMany()
                        .HasForeignKey("EtatAlerteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AlertSystem.Entities.Entities.DefUtilisateur", "Expediteur")
                        .WithMany()
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AlertSystem.Entities.Entities.PlateformeEnvoie", "PlateformeEnvoie")
                        .WithMany()
                        .HasForeignKey("PlateformeEnvoieId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AlertSystem.Entities.Entities.PlateformeEnvoie", null)
                        .WithMany("Alertes")
                        .HasForeignKey("PlateformeEnvoiePlateformeId");

                    b.HasOne("AlertSystem.Entities.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AlertType");

                    b.Navigation("DestinataireUser");

                    b.Navigation("Etat");

                    b.Navigation("Expediteur");

                    b.Navigation("PlateformeEnvoie");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.RappelSuivant", b =>
                {
                    b.HasOne("AlertSystem.Entities.Entities.Alerte", "Alerte")
                        .WithMany("Rappels")
                        .HasForeignKey("AlerteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerte");
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.Alerte", b =>
                {
                    b.Navigation("Rappels");
                });

            modelBuilder.Entity("AlertSystem.Entities.Entities.PlateformeEnvoie", b =>
                {
                    b.Navigation("Alertes");
                });
#pragma warning restore 612, 618
        }
    }
}
