using System;
using System.Text;

namespace AlertSystem.Service
{
    public interface IEmailTemplateService
    {
        string CreateAlertEmailTemplate(string title, string message, string senderName, DateTime timestamp, string confirmationUrl);
    }

    public class EmailTemplateService : IEmailTemplateService
    {
        public string CreateAlertEmailTemplate(string title, string message, string senderName, DateTime timestamp, string confirmationUrl)
        {
            var html = new StringBuilder();
            
            html.AppendLine("<!DOCTYPE html>");
            html.AppendLine("<html lang=\"fr\">");
            html.AppendLine("<head>");
            html.AppendLine("    <meta charset=\"UTF-8\">");
            html.AppendLine("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
            html.AppendLine("    <title>Notification d'Alerte</title>");
            html.AppendLine("    <style>");
            html.AppendLine("        body {");
            html.AppendLine("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;");
            html.AppendLine("            line-height: 1.6;");
            html.AppendLine("            color: #333;");
            html.AppendLine("            max-width: 600px;");
            html.AppendLine("            margin: 0 auto;");
            html.AppendLine("            padding: 20px;");
            html.AppendLine("            background-color: #f4f4f4;");
            html.AppendLine("        }");
            html.AppendLine("        .container {");
            html.AppendLine("            background: white;");
            html.AppendLine("            border-radius: 10px;");
            html.AppendLine("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);");
            html.AppendLine("            overflow: hidden;");
            html.AppendLine("        }");
            html.AppendLine("        .header {");
            html.AppendLine("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);");
            html.AppendLine("            color: white;");
            html.AppendLine("            padding: 30px;");
            html.AppendLine("            text-align: center;");
            html.AppendLine("        }");
            html.AppendLine("        .header h1 {");
            html.AppendLine("            margin: 0;");
            html.AppendLine("            font-size: 28px;");
            html.AppendLine("            font-weight: 300;");
            html.AppendLine("        }");
            html.AppendLine("        .content {");
            html.AppendLine("            padding: 30px;");
            html.AppendLine("        }");
            html.AppendLine("        .alert-title {");
            html.AppendLine("            font-size: 24px;");
            html.AppendLine("            color: #2c3e50;");
            html.AppendLine("            margin-bottom: 20px;");
            html.AppendLine("            font-weight: 600;");
            html.AppendLine("        }");
            html.AppendLine("        .alert-message {");
            html.AppendLine("            background: #f8f9fa;");
            html.AppendLine("            border-left: 4px solid #667eea;");
            html.AppendLine("            padding: 20px;");
            html.AppendLine("            margin: 20px 0;");
            html.AppendLine("            border-radius: 0 5px 5px 0;");
            html.AppendLine("            font-size: 16px;");
            html.AppendLine("            line-height: 1.8;");
            html.AppendLine("        }");
            html.AppendLine("        .alert-details {");
            html.AppendLine("            background: #e8f4f8;");
            html.AppendLine("            padding: 20px;");
            html.AppendLine("            border-radius: 8px;");
            html.AppendLine("            margin: 20px 0;");
            html.AppendLine("        }");
            html.AppendLine("        .detail-row {");
            html.AppendLine("            display: flex;");
            html.AppendLine("            justify-content: space-between;");
            html.AppendLine("            margin: 10px 0;");
            html.AppendLine("            padding: 8px 0;");
            html.AppendLine("            border-bottom: 1px solid #d1ecf1;");
            html.AppendLine("        }");
            html.AppendLine("        .detail-row:last-child {");
            html.AppendLine("            border-bottom: none;");
            html.AppendLine("        }");
            html.AppendLine("        .detail-label {");
            html.AppendLine("            font-weight: 600;");
            html.AppendLine("            color: #495057;");
            html.AppendLine("        }");
            html.AppendLine("        .detail-value {");
            html.AppendLine("            color: #6c757d;");
            html.AppendLine("        }");
            html.AppendLine("        .confirm-button {");
            html.AppendLine("            display: inline-block;");
            html.AppendLine("            background: linear-gradient(135deg, #28a745 0%, #20c997 100%);");
            html.AppendLine("            color: white;");
            html.AppendLine("            padding: 15px 30px;");
            html.AppendLine("            text-decoration: none;");
            html.AppendLine("            border-radius: 25px;");
            html.AppendLine("            font-weight: 600;");
            html.AppendLine("            font-size: 16px;");
            html.AppendLine("            margin: 20px 0;");
            html.AppendLine("            text-align: center;");
            html.AppendLine("            box-shadow: 0 4px 15px rgba(40, 167, 69, 0.3);");
            html.AppendLine("            transition: all 0.3s ease;");
            html.AppendLine("        }");
            html.AppendLine("        .confirm-button:hover {");
            html.AppendLine("            transform: translateY(-2px);");
            html.AppendLine("            box-shadow: 0 6px 20px rgba(40, 167, 69, 0.4);");
            html.AppendLine("        }");
            html.AppendLine("        .footer {");
            html.AppendLine("            background: #f8f9fa;");
            html.AppendLine("            padding: 20px;");
            html.AppendLine("            text-align: center;");
            html.AppendLine("            color: #6c757d;");
            html.AppendLine("            font-size: 14px;");
            html.AppendLine("        }");
            html.AppendLine("        .priority-high {");
            html.AppendLine("            border-left-color: #dc3545;");
            html.AppendLine("        }");
            html.AppendLine("        .priority-medium {");
            html.AppendLine("            border-left-color: #ffc107;");
            html.AppendLine("        }");
            html.AppendLine("        .priority-low {");
            html.AppendLine("            border-left-color: #28a745;");
            html.AppendLine("        }");
            html.AppendLine("        @media (max-width: 600px) {");
            html.AppendLine("            body {");
            html.AppendLine("                padding: 10px;");
            html.AppendLine("            }");
            html.AppendLine("            .content {");
            html.AppendLine("                padding: 20px;");
            html.AppendLine("            }");
            html.AppendLine("            .header {");
            html.AppendLine("                padding: 20px;");
            html.AppendLine("            }");
            html.AppendLine("            .alert-title {");
            html.AppendLine("                font-size: 20px;");
            html.AppendLine("            }");
            html.AppendLine("        }");
            html.AppendLine("    </style>");
            html.AppendLine("</head>");
            html.AppendLine("<body>");
            html.AppendLine("    <div class=\"container\">");
            html.AppendLine("        <div class=\"header\">");
            html.AppendLine("            <h1>🚨 Notification d'Alerte</h1>");
            html.AppendLine("        </div>");
            html.AppendLine("        <div class=\"content\">");
            html.AppendLine($"            <div class=\"alert-title\">{title}</div>");
            html.AppendLine("            <div class=\"alert-message\">");
            html.AppendLine($"                {message.Replace("\n", "<br>")}");
            html.AppendLine("            </div>");
            html.AppendLine("            <div class=\"alert-details\">");
            html.AppendLine("                <div class=\"detail-row\">");
            html.AppendLine("                    <span class=\"detail-label\">📅 Date de création:</span>");
            html.AppendLine($"                    <span class=\"detail-value\">{timestamp:dd/MM/yyyy HH:mm:ss}</span>");
            html.AppendLine("                </div>");
            html.AppendLine("                <div class=\"detail-row\">");
            html.AppendLine("                    <span class=\"detail-label\">👤 Expéditeur:</span>");
            html.AppendLine($"                    <span class=\"detail-value\">{senderName}</span>");
            html.AppendLine("                </div>");
            html.AppendLine("                <div class=\"detail-row\">");
            html.AppendLine("                    <span class=\"detail-label\">📧 Type:</span>");
            html.AppendLine("                    <span class=\"detail-value\">Notification par email</span>");
            html.AppendLine("                </div>");
            html.AppendLine("            </div>");
            html.AppendLine("            <div style=\"text-align: center; margin: 30px 0;\">");
            html.AppendLine($"                <a href=\"{confirmationUrl}\" class=\"confirm-button\">");
            html.AppendLine("                    ✅ Confirmer la réception");
            html.AppendLine("                </a>");
            html.AppendLine("            </div>");
            html.AppendLine("            <div style=\"background: #fff3cd; border: 1px solid #ffeaa7; border-radius: 5px; padding: 15px; margin: 20px 0; color: #856404;\">");
            html.AppendLine("                <strong>ℹ️ Information importante:</strong>");
            html.AppendLine("                <br>Veuillez cliquer sur le bouton de confirmation ci-dessus pour marquer cette alerte comme lue. Cela nous permettra de suivre l'état de traitement de cette notification.");
            html.AppendLine("            </div>");
            html.AppendLine("        </div>");
            html.AppendLine("        <div class=\"footer\">");
            html.AppendLine("            <p>Cette notification a été envoyée automatiquement par le système d'alerte.</p>");
            html.AppendLine("            <p>Si vous n'êtes pas destinataire de cette alerte, veuillez ignorer ce message.</p>");
            html.AppendLine("        </div>");
            html.AppendLine("    </div>");
            html.AppendLine("</body>");
            html.AppendLine("</html>");

            return html.ToString();
        }
    }
}
