# Test API Key Workflow Script
# This script tests the complete API key authentication workflow

param(
    [string]$ApiBaseUrl = "http://localhost:5002",
    [string]$Server = "(localdb)\\MSSQLLocalDB",
    [string]$Database = "BELVEDERE_17_10_2025"
)

Write-Host "=== API Key Workflow Test ===" -ForegroundColor Cyan
Write-Host "Testing API key authentication system..." -ForegroundColor Yellow

# Test 1: Generate a new API key
Write-Host "`n1. Generating new API key..." -ForegroundColor Green
$keyOutput = & ".\scripts\generate-api-key.ps1" -Name "Test Client $(Get-Date -Format 'yyyyMMdd-HHmmss')" -Server $Server -Database $Database
$apiKey = ($keyOutput | Select-String "PLAINTEXT API KEY").Line.Split(':')[1].Trim()

if ($apiKey) {
    Write-Host "âœ… API key generated: $($apiKey.Substring(0, 8))..." -ForegroundColor Green
} else {
    Write-Host "âŒ Failed to generate API key" -ForegroundColor Red
    exit 1
}

# Test 2: Validate the API key
Write-Host "`n2. Testing API key validation..." -ForegroundColor Green
try {
    $headers = @{
        "X-API-KEY" = $apiKey
        "Content-Type" = "application/json"
    }
    
    $response = Invoke-RestMethod -Uri "$ApiBaseUrl/api/v1/keys/validate" -Method GET -Headers $headers
    
    if ($response.valid) {
        Write-Host "âœ… API key validation successful" -ForegroundColor Green
        Write-Host "   Response: $($response.message)" -ForegroundColor Gray
    } else {
        Write-Host "âŒ API key validation failed" -ForegroundColor Red
    }
} catch {
    Write-Host "âŒ API key validation error: $($_.Exception.Message)" -ForegroundColor Red
}

# Test 3: Test API call with valid key
Write-Host "`n3. Testing API call with valid key..." -ForegroundColor Green
try {
    $body = @{
        title = "Test Alert from PowerShell"
        message = "This is a test alert generated by the API key workflow test"
        alertType = "acquittementNonNÃ©cessaire"
        expedType = "Service"
        appId = 1
        recipients = @(
            @{
                recipientId = "test@example.com"
                type = "email"
            }
        )
    } | ConvertTo-Json -Depth 3
    
    $response = Invoke-RestMethod -Uri "$ApiBaseUrl/api/v1/alerts" -Method POST -Headers $headers -Body $body
    
    Write-Host "âœ… API call successful" -ForegroundColor Green
    Write-Host "   Alert ID: $($response.alertId)" -ForegroundColor Gray
    Write-Host "   Overall Success: $($response.overallSuccess)" -ForegroundColor Gray
} catch {
    Write-Host "âŒ API call error: $($_.Exception.Message)" -ForegroundColor Red
}

# Test 4: Test with invalid API key
Write-Host "`n4. Testing with invalid API key..." -ForegroundColor Green
try {
    $invalidHeaders = @{
        "X-API-KEY" = "invalid-key-12345"
        "Content-Type" = "application/json"
    }
    
    $response = Invoke-RestMethod -Uri "$ApiBaseUrl/api/v1/keys/validate" -Method GET -Headers $invalidHeaders
    
    Write-Host "âŒ Invalid key was accepted (this should not happen)" -ForegroundColor Red
} catch {
    if ($_.Exception.Response.StatusCode -eq 403) {
        Write-Host "âœ… Invalid API key correctly rejected (403 Forbidden)" -ForegroundColor Green
    } elseif ($_.Exception.Response.StatusCode -eq 401) {
        Write-Host "âœ… Invalid API key correctly rejected (401 Unauthorized)" -ForegroundColor Green
    } else {
        Write-Host "âš ï¸  Unexpected error with invalid key: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

# Test 5: Test without API key
Write-Host "`n5. Testing without API key..." -ForegroundColor Green
try {
    $noKeyHeaders = @{
        "Content-Type" = "application/json"
    }
    
    $response = Invoke-RestMethod -Uri "$ApiBaseUrl/api/v1/keys/validate" -Method GET -Headers $noKeyHeaders
    
    Write-Host "âŒ Request without API key was accepted (this should not happen)" -ForegroundColor Red
} catch {
    if ($_.Exception.Response.StatusCode -eq 401) {
        Write-Host "âœ… Request without API key correctly rejected (401 Unauthorized)" -ForegroundColor Green
    } else {
        Write-Host "âš ï¸  Unexpected error without API key: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

Write-Host "`n=== API Key Workflow Test Complete ===" -ForegroundColor Cyan
Write-Host "Generated API key: $($apiKey.Substring(0, 8))..." -ForegroundColor Yellow
Write-Host "Keep this key safe for future testing!" -ForegroundColor Yellow

